# Generated by Django 4.2.2 on 2023-07-03 01:51

import currency.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('market_cup', models.CharField(max_length=50)),
                ('difference', models.CharField(max_length=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='example_username', max_length=100, unique=True)),
                ('email', models.EmailField(default='example@mail.ru', max_length=100)),
                ('password', models.CharField(default='12345678', max_length=50)),
                ('register_time', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chosen_coins', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=currency.models.default_chosen_coins, size=None)),
                ('access_level', models.CharField(choices=[(1, 'moderator'), (2, 'user')], default='user', max_length=20)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
